name: run Rpa-Wm-Version2.py

on:
  schedule:
    - cron: '* 2 * * *'

jobs:
  run_schedule:
    runs-on: ubuntu-latest
    steps:

      - name: check conteudo do repositorio
        uses: actions/checkout@v3

      - name: instalar python
        uses: actions/setup-python@v3

      - name: instalar Selenium
        run: pip3 install selenium

      - name: instalar web driver
        run: pip install webdriver-manager

      - name: instalar Pandas
        run: pip install pandas

      

      - name: instalar os todos os pacotes
        run: python - m pip install pip install -r requirements.txt
       

      - name: executar arquivo de scrapping
        run: python Rpa-Wm.py
          

      - name: Commit and push File csv
        run: |-
          git config --global user.name "Romeriogomes"
          git config --global user.email "jose.romerio.soares@gmail.com"
          git fetch
          git add relatorio.csv
          git commit -m "Arquivo atualizado"
          git push
